/**
 * ID Generation Utilities
 *
 * Centralized unique ID generation for consistent format across the application.
 * Format: [prefix-]timestamp-randomSuffix
 *
 * @example
 * ```typescript
 * generateId() // "1704067200000-a1b2c3d"
 * generateId('history') // "history-1704067200000-a1b2c3d"
 * generateId('custom') // "custom-1704067200000-a1b2c3d"
 * ```
 */

/**
 * Generate a unique ID with optional prefix
 *
 * Creates a collision-resistant ID using timestamp and random suffix.
 * The random suffix uses base-36 encoding for compact representation.
 *
 * @param prefix - Optional prefix to prepend to the ID (e.g., 'history', 'custom')
 * @returns Unique ID string in format: [prefix-]timestamp-randomSuffix
 *
 * @example
 * ```typescript
 * // Without prefix
 * const id = generateId();
 * console.log(id); // "1704067200000-a1b2c3d"
 *
 * // With prefix
 * const historyId = generateId('history');
 * console.log(historyId); // "history-1704067200000-a1b2c3d"
 * ```
 */
export const generateId = (prefix?: string): string => {
  const timestamp = Date.now();
  const random = Math.random().toString(36).substring(2, 9);

  return prefix ? `${prefix}-${timestamp}-${random}` : `${timestamp}-${random}`;
};

/**
 * Generate a history entry ID
 *
 * Specialized version of generateId for history entries.
 * Provides consistent format for history-related IDs.
 *
 * @returns Unique history ID in format: "history-timestamp-randomSuffix"
 *
 * @example
 * ```typescript
 * const historyId = generateHistoryId();
 * console.log(historyId); // "history-1704067200000-a1b2c3d"
 * ```
 */
export const generateHistoryId = (): string => {
  return generateId('history');
};

/**
 * Generate a custom keyword ID
 *
 * Specialized version of generateId for custom keywords.
 * Provides consistent format for custom keyword IDs.
 *
 * @returns Unique custom keyword ID in format: "custom-timestamp-randomSuffix"
 *
 * @example
 * ```typescript
 * const keywordId = generateCustomKeywordId();
 * console.log(keywordId); // "custom-1704067200000-a1b2c3d"
 * ```
 */
export const generateCustomKeywordId = (): string => {
  return generateId('custom');
};

/**
 * Extract timestamp from ID
 *
 * Parses an ID to extract the embedded timestamp.
 * Useful for sorting or filtering by creation time.
 *
 * @param id - ID string generated by generateId
 * @returns Timestamp in milliseconds, or null if parsing fails
 *
 * @example
 * ```typescript
 * const id = generateId('history');
 * const timestamp = extractTimestamp(id);
 * console.log(new Date(timestamp)); // Current date/time
 * ```
 */
export const extractTimestamp = (id: string): number | null => {
  try {
    // Split by hyphen and find the timestamp part
    const parts = id.split('-');

    // Find the part that looks like a timestamp (13-digit number)
    const timestampPart = parts.find((part) => /^\d{13}$/.test(part));

    if (timestampPart) {
      return parseInt(timestampPart, 10);
    }

    return null;
  } catch {
    return null;
  }
};

/**
 * Validate ID format
 *
 * Checks if a string matches the expected ID format.
 *
 * @param id - String to validate
 * @returns true if valid ID format, false otherwise
 *
 * @example
 * ```typescript
 * isValidId('history-1704067200000-a1b2c3d'); // true
 * isValidId('invalid-id'); // false
 * ```
 */
export const isValidId = (id: string): boolean => {
  // Pattern: [prefix-]timestamp-randomSuffix
  // timestamp: 13-digit number
  // randomSuffix: 7 alphanumeric characters
  const pattern = /^(?:[a-z]+-)?(\d{13})-([a-z0-9]{7})$/;
  return pattern.test(id);
};
